### ISSUE TITLE
data build issues

### ISSUE THREAD

**Issue by backslashpaige** [drofphilosophe/USElecData#32]
First error:

Error: Could not find associated project in working directory or any parent directory.
- Path in project: src/EIA-Form860/loadEIA860_Schedule6_BoilerStack.R
- Current working directory: /Users/paigeweber/Git/USElecData
Please open the project associated with this file and try again.
Execution halted
----- End R script src/EIA-Form860/loadEIA860_Schedule3_Generators.R -----

Second error:

Error: Could not find associated project in working directory or any parent directory.
- Path in project: src/EPA-CEMS/loadEIA860_Schedule6_BoilerStack.R
- Current working directory: /Users/paigeweber/Git/USElecData
Please open the project associated with this file and try again.
Execution halted
----- End R script src/EIA-Form860/loadEIA860_Schedule6.R -----

Third error:

Error in library(units) : there is no package called ‘units’
Execution halted

Fourth error:

Error in library(sf) : there is no package called ‘sf’
Execution halted
----- End R script src/EPA-CEMS/loadFacilityData.R -----

Fifth error:

here() starts at /Users/paigeweber/Git/USElecData
Error in readRDS(con, refhook = refhook) : cannot open the connection
Calls: read_rds -> readRDS
In addition: Warning message:
In readRDS(con, refhook = refhook) :
  cannot open file '/Users/paigeweber/Dropbox/USElecData/data/out/crosswalks/rds/CEMSToEIAUnitGrouping.rds.gz': No such file or directory
Execution halted
----- End R script src/EPA-CEMS/netToGrossCalculation.R -----

**Comment by drofphilosophe** [comment]
It seems like later code in the 860 build requries the crosswalks, but you need the earlier 860 stuff to build crosswalks

**Comment by drofphilosophe** [comment]
It turns out I think this was a problem with the `i_am()` commands a the start of these R scripts. They were pointing to old file names that don't exist in the new repo. Scripts should fail when they can't find the file referenced by `i_am()`.  I've pushed changes to fix that.

The missing units and sf packages errors are from not having the proper packages installed in R. I've removed references to the units package -- we don't need it anymore -- but you should have installed the sf package when you ran `USElecData.sh init`. You can try running init again and see if that fixes it. Alternatively, you can open an R session in your anaconda environment and run the command `install.packages("sf")`. I have also updated the init script to install the r-sf package as part of the conda environment.

**Comment by backslashpaige** [comment]
Okay re-running and now and got this error below. thinking maybe that  860.R file should be in the 860 directory?

**Error: Could not find associated project in working directory or any parent directory.
- Path in project: src/EPA-CEMS/loadEIA860_Schedule6_BoilerStack.R
- Current working directory: /Users/paigeweber/Git/USElecData**

**Comment by drofphilosophe** [comment]
The problem would be that R can't seem to file the referenced code file. I don't see that file reference (`src/EPA-CEMS/loadEIA860_Schedule6_BoilerStack.R`) anywhere in my repo. I've merged some changes into main that fixed bad file references. Are you working from main or have you rebased your branch to main recently? That should fix it.

**Comment by drofphilosophe** [comment]
This error was likely the result of the management script continuing to run additional subprocesses even after one failed. I have changed the behavior of the management script to fail if any subprocess exits prematurely. If this error comes up again, we should open a new issue.
