### ISSUE TITLE
script path

### ISSUE THREAD

**Issue by backslashpaige** [drofphilosophe/USElecData#6]
https://github.com/drofphilosophe/USElecData/blob/f04673ba0ab2d2257f108b3ce278fdb2b94ee5b0/src/EIA-Form860/getEIAForm860.py#L18

script path has extra ".." for paige

**Comment by drofphilosophe** [comment]
I've pushed a change, let me know if it works (because I'll need to change other files too). 

If it doesn't work: What does the file structure where this script is located look like? And how are you running the script?

`projectRoot` exists so the script can find the configuration files which should be in the root directory of the project (I call mine `USElecData`). This script should be in `USElecData/src/EIA-Form860`, so it should need to navigate up two directories to find it. If your file layout is different I'll need to figure out why (since it's just the pulled repo). If you have the same file layout, the script isn't correctly determining its location and I'll need to sort that out.
